version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-lab-prod
    restart: always
    environment:
      MYSQL_DATABASE: 'lab_system_db'
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_PASSWORD: 'admin123'
    volumes:
      - mysql_data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d/
    ports:
      - '3310:3306'
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin123"]
      timeout: 20s
      retries: 10
      start_period: 40s
    networks:
      - backend

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: lab_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8085:8085'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/lab_system_db?serverTimezone=America/Lima&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    name: lab_network
