name: Deploy Lab System Locally

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_PROJECT_NAME: 'labproject'
  APP_CONTAINER_NAME: 'lab_app'
  DB_CONTAINER_NAME: 'mysql-lab-prod'
  DB_NAME: 'lab_system_db'
  DB_USER: 'root'
  DB_PASSWORD: 'admin123'

jobs:
  build-and-deploy:
    name: Build and Deploy Lab System
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Deploy with Docker Compose
        run: |
          echo "🚀 Iniciando despliegue..."
          cd docker

          echo "🧹 Eliminando contenedores antiguos..."
          docker-compose -p ${{ env.DOCKER_PROJECT_NAME }} down -v --remove-orphans || echo "Nada que limpiar"

          echo "🔨 Construyendo y desplegando..."
          docker-compose -p ${{ env.DOCKER_PROJECT_NAME }} up -d --build

          echo "⏳ Esperando 30 segundos..."
          sleep 30

          echo "💾 Ejecutando init.sql si existe..."
          if [ -f ../sql/init.sql ]; then
            docker exec -i ${{ env.DB_CONTAINER_NAME }} mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} ${{ env.DB_NAME }} < ../sql/init.sql
          else
            echo "⚠️ init.sql no encontrado. Continuando sin datos iniciales."
          fi

          echo "🔍 Logs recientes:"
          docker logs --tail 100 ${{ env.APP_CONTAINER_NAME }}

          echo "✅ Despliegue finalizado."
